import type { Metadata } from "next";
import "../globals.css";
import ReduxProvider from "@/components/Providers/Reduxprovider";
import SidebarComp from "@/components/Sidebar/Sidebar";
import { Manrope } from "next/font/google";

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${manRope.variable} admin`}>
        <ReduxProvider>
          <SidebarComp>{children}</SidebarComp>
        </ReduxProvider>
      </body>
    </html>
  );
}
