import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "../../../globals.css";
const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section className={manRope.variable}>{children}</section>;
}
